apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-airport-paas
  labels:
    app: argo-airport-paas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argo-airport-paas
  template:
    metadata:
      labels:
        app: argo-airport-paas
    spec:
      containers:
        - name: argo-airport-paas
          image: ghcr.io/3kmfi6hp/argo-airport-paas:main
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: config-env
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "1"
              memory: "1024Mi"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: argo-airport-paas-lb
spec:
  type: LoadBalancer
  ports:
    - port: 8580
      targetPort: 3000
  selector:
    app: argo-airport-paas
